[WIP] Add LeftRightMotors Subsystem
FRC1076/2017-Pickup pull request #2
Opened 2016-11-19 18:35 UTC by ellazzhang

This subsystem controls the left and right wheel motors. It can move the robot forwards, move the robot backwards, and make the robot turn.

2016-11-19 23:50 UTC, porglezomp requested changes
Add doc comments

2016-11-19 23:50 UTC, porglezomp commented on src/org/usfirst/frc/team1076/robot/subsystems/LeftRightMotors.java
> +	public void setLeftSpeed(double speed) {
It would be good to have doc comments on each of these functions.

2016-11-20 17:23 UTC, porglezomp requested changes
There are some final minor improvements you can make to the documentation, but it's almost there.

2016-11-20 17:23 UTC, porglezomp commented on src/org/usfirst/frc/team1076/robot/subsystems/LeftRightMotors.java
> +	 * sets the speed of the left motor
These look pretty good, but there are two things I would change:
- Document the expected range for `speed` (-1 to 1)
- Capitalize and punctuate all the documentation.

2016-12-01 00:37 UTC, anish2399 approved these changes
This code looks good.

2016-12-01 00:38 UTC, porglezomp approved these changes

2016-12-01 00:38 UTC, porglezomp commented on src/org/usfirst/frc/team1076/robot/subsystems/LeftRightMotors.java
> +	 * sets the speed of the left motor
I'm going to have Anish make these changes.

2016-12-01 01:04 UTC, porglezomp approved these changes
These are helpful doc comment improvements, this looks good.

2016-12-01 01:05 UTC, merged