[WIP] Add FrontBackMotors subsystem
FRC1076/2017-Pickup pull request #3
Opened 2016-11-19 18:35 UTC by coedx

This adds the "FrontBackMotors" subsystem which is for controlling the front and back wheels and letting the robot move forward and backward.

2016-11-19 23:51 UTC, porglezomp approved these changes
You should add doc comments to these

2016-11-19 23:51 UTC, porglezomp requested changes
You should add doc comments

2016-12-01 01:05 UTC, anish2399 approved these changes
This looks good.

2016-12-01 01:05 UTC, porglezomp approved these changes

2016-12-01 01:06 UTC, merged